### ISSUE TITLE
Uuid primary keys are initialized with zeros.

### ISSUE THREAD

**Issue by wvffle** [weldsorm/welds#27]
When saving the model with the following code, the `user.id is set to a zeroed Uuid. 

```rs
#[derive(WeldsModel)]
struct User {
  #[welds(primary_key)]
  id: Uuid,
  username: String
}

let mut user = User::new();
user.username = "test".into();
user.save(client).await?;
dbg!(user.id);
```

My table has the id field declared as follows and it should set the uuid automatically but welds passes the `Uuid::default()` value which is equivalent to `Uuid::nil()`.

```sql
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(128) NOT NULL
);
```

**Comment by lex148** [comment]
interesting, that doesn't sound right. I will go take a look. it looks like you are using a postgres backend correct?

**Comment by wvffle** [comment]
Thanks for quick reaction! :)

>  it looks like you are using a postgres backend correct?

Yes.

**Comment by lex148** [comment]
Fix for your issue is out in `v0.3.6`

Welds was expecting all UUIDs to be defined outside the database. This is no longer the case. I wanted to continue to support that use case as well as UUIDs from the database. Currently if you see a value to the UUID in your model it will save that as the ID for your model. If you leave it the default zeroed value, It is expecting the UUID to come from the database.

**Comment by wvffle** [comment]
Unfortunately, the `WeldsModel` macro in the new version seems to mishandle angle brackets with const values.

![image](https://github.com/user-attachments/assets/152276ee-50d5-4284-872f-07ff85dd9336)

Changing the type to `Bits::<7>` seems a bit odd, but after doing so, rustfmt automaticaly changes it back to `Bits<7>`.


Note:

The `#[model]` macro (underlined in the error message)  is my own macro that adds the derive for `WeldsModel` and implements some methods for the model

**Comment by lex148** [comment]
This one was one me. I wasn't handling generic types correctly. fix is up now

**Comment by wvffle** [comment]
Now it works perfectly fine, thank you!
