### ISSUE TITLE
docs.rs failed to build welds-connections-0.3.7 

### ISSUE THREAD

**Issue by wvffle** [weldsorm/welds#29]
https://docs.rs/crate/welds-connections/latest

**Comment by cmorgan-NN** [comment]
This is still not working. I'd like to use welds, but it will not build in my project. It is giving the same errors as the above link.

**Comment by lex148** [comment]
hey @cmorgan-NN 

So this is an interesting bug ticket. It is specifically referring to `welds-connections` and building the docs on `docs.rs`. The problem in `docs.rs` is that no database feature is enabled. I am reluctant to just enable all database drivers for everyone just for `docs.rs`. I will look into this some more. 

If this really is your issue. Just running cargo add with the right feature would fix it. 
```
# all database drivers
cargo add welds --features=sqlite,postgres,mysql,mssql
# or just a specific one
cargo add welds --features=postgres
```
 
If this isn't your issue, I would still like to help. Could you give me a little more info about the error you are seeing?

**Comment by lex148** [comment]
Just needed to put the features in the config for doc... 🤦 docs.rs is now fixed

**Comment by cmorgan-NN** [comment]
Thanks for the reply. Yes, I was able to resolve this with adding mssql as a feature. Sorry if this was in the docs and I didn't see it.

**Comment by cmorgan-NN** [comment]
Sweet, hopefully this also closes this issue and fixed mine! Thanks again.

**Comment by lex148** [comment]
No, all good. Awesome glad its working for you. have fun playing with Welds !!!
