### ISSUE TITLE
Add support for sqlx 0.8.0

### ISSUE THREAD

**Issue by wvffle** [weldsorm/welds#33]
Recently sqlx 0.8.0 got released. Changelog: https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md

**Comment by lex148** [comment]
I am on it. looks like it shouldn't take to long

**Comment by lex148** [comment]
sqlx 0.8 version is up and merged onto main. I plan on doing a bit more verification, and it should be out for the release in the morning.
